//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Package1 {
  using System;
  using System.Collections;
  using System.Collections.Generic;
  using System.CodeDom.Compiler;
  using Eco.ObjectRepresentation;
  using Eco.ObjectImplementation;
  using Eco.Services;
  using Eco.Subscription;
  using Eco.UmlCodeAttributes;
  using Eco.UmlRt;
  
  
  [UmlElement("Package", Id="ec91c593-f532-47e4-8fae-c7c3445a8800")]
  [UmlTaggedValue("Eco.ModeledName", "Package1")]
  [GeneratedCodeAttribute("ECO", "7.1.0.0")]
  [UmlMetaAttribute("ownedElement", typeof(Package1.Class2))]
  [UmlMetaAttribute("ownedElement", typeof(Package1.Class1))]
  public abstract partial class Package1Package {
    
    [UmlElement("Association", Id="9bedca2e-dea2-4c10-b735-84b4eb5562f6")]
    [GeneratedCodeAttribute("ECO", "7.1.0.0")]
    public class Class2Class2Class1Class1 {
    }
  }
}
